HealthCheck/Health.Web/Models/WebApiUrls.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace Health.Web.Models
{
    public class WebApiUrls
    {
        public static string HealthCurrentGetCurrentView
        {
            get
            {
                return GetValue("HealthCurrentGetCurrentView", "HealthCurrent/GetCurrentView");
            }
        }

        public static string HealthHisSearch
        {
            get
            {
                return GetValue("HealthHisSearch", "HealthHis/Search");
            }
        }

        public static string HealthHis2Search
        {
            get
            {
                return GetValue("HealthHis2Search", "HealthHis2/Search");
            }
        }

        public static string HealthTargetCreate
        {
            get
            {
                return GetValue("HealthTargetCreate", "HealthTarget/Create");
            }
        }

        public static string HealthTargetDelete
        {
            get
            {
                return GetValue("HealthTargetDelete", "HealthTarget/Delete");
            }
        }

        public static string HealthTargetUpdate
        {
            get
            {
                return GetValue("HealthTargetUpdate", "HealthTarget/Update");
            }
        }

        public static string HealthTargetSearch
        {
            get
            {
                return GetValue("HealthTargetSearch", "HealthTarget/Search");
            }
        }

        public static string NotificationInfoCreate
        {
            get
            {
                return GetValue("NotificationInfoCreate", "NotificationInfo/Create");
            }
        }

        public static string NotificationInfoDelete
        {
            get
            {
                return GetValue("NotificationInfoDelete", "NotificationInfo/Delete");
            }
        }

        public static string NotificationInfoUpdate
        {
            get
            {
                return GetValue("NotificationInfoUpdate", "NotificationInfo/Update");
            }
        }

        public static string NotificationInfoSearch
        {
            get
            {
                return GetValue("NotificationInfoSearch", "NotificationInfo/Search");
            }
        }

        public static string SystemInfoSearch
        {
            get
            {
                return GetValue("SystemInfoSearch", "SystemInfo/Search");
            }
        }

        public static string SystemInfoCreate
        {
            get
            {
                return GetValue("SystemInfoCreate", "SystemInfo/Create");
            }
        }

        public static string SystemInfoDelete
        {
            get
            {
                return GetValue("SystemInfoDelete", "SystemInfo/Delete");
            }
        }

        public static string SystemInfoUpdate
        {
            get
            {
                return GetValue("SystemInfoUpdate", "SystemInfo/Update");
            }
        }

        public static string SystemInfoUpdateThreshold
        {
            get
            {
                return GetValue("SystemInfoUpdateThreshold", "SystemInfo/UpdateThreshold");
            }
        }

        public static string UserTokenGetCurrentUsers
        {
            get
            {
                return GetValue("UserTokenGetCurrentUsers", "UserToken/GetCurrentUsers");
            }
        }

        public static string VMInfoCreate
        {
            get
            {
                return GetValue("VMInfoCreate", "VMInfo/Create");
            }
        }

        public static string VMInfoDelete
        {
            get
            {
                return GetValue("VMInfoDelete", "VMInfo/Delete");
            }
        }

        public static string VMInfoUpdate
        {
            get
            {
                return GetValue("VMInfoUpdate", "VMInfo/Update");
            }
        }

        public static string VMInfoSearch
        {
            get
            {
                return GetValue("VMInfoSearch", "VMInfo/Search");
            }
        }

        private static string WebApiUrlRoot
        {
            get
            {
                string value = GetValue("WebApiUrlRoot", string.Empty);
                if (value[value.Length - 1] != '/')
                    value += "/";

                return value;
            }
        }

        private static string GetValue(string key, string defaultValue)
        {
            string value = defaultValue;
            if (ConfigurationManager.AppSettings.AllKeys.Contains(key))
                value = ConfigurationManager.AppSettings[key];

            return value.Contains("://") || value.Contains("~/") ? value : string.Format("{0}{1}", WebApiUrlRoot, value);
        }
    }
}

HealthCheck/Health.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Health.Web.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("SystemInfo");
        }

        public ActionResult SystemInfo()
        {
            return View();
        }

        public ActionResult HealthTarget()
        {
            return View();
        }

        public ActionResult NotificationInfo()
        {
            return View();
        }

        public ActionResult VMInfo()
        {
            return View();
        }
    }
}

HealthCheck/Health.Web/Controllers/RptController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Health.API.Models;

namespace Health.Web.Controllers
{
    public class RptController : Controller
    {
        public static int RefreshInterval
        {
            get
            {
                if (!string.IsNullOrEmpty(ConfigurationManager.AppSettings["RefreshInterval"]))
                    return Convert.ToInt32(ConfigurationManager.AppSettings["RefreshInterval"]);
                else
                    return 60000;
            }
        }

        public ActionResult EMIC2_Current()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EMIC2_His(HealthHisModel healthCurrentView)
        {
            return View(healthCurrentView);
        }

        [HttpPost]
        public ActionResult EMIC2_His2(HealthHisModel healthCurrentView)
        {
            return View(healthCurrentView);
        }
    }
}

HealthCheck/Health.Web/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

HealthCheck/Health.Web/Views/Rpt/EMIC2_Current.cshtml
@using Health.Web.Controllers
@using Health.Web.Models
@{
    ViewBag.Title = "APM監控儀表板-主機狀態";
}
@section styles {
    <style type="text/css">
        #healthCurrent.row {
            display: flex;
            flex-wrap: wrap;
        }

        #healthCurrent.row > [class*='col-'] {
            display: flex;
            flex-direction: column;
        }
    </style>
}
@section scripts {
    <script type="text/javascript">
        $(function () {
            $("#alerts")
                .on("hide.bs.modal", function () {
                    var sound = document.getElementById("sound");
                    sound.pause();
                });

            refreshHealthCurrentView();
            refreshCurrentUser();

            setInterval(function () {
                refreshHealthCurrentView();
                refreshCurrentUser();
            }, @RptController.RefreshInterval);
        });

        function rowOnClick(systemID, systemName, vmID) {
            $("input[name='SYSTEM_ID']").val(systemID);
            $("input[name='SYSTEM_NAME']").val(systemName);
            $("input[name='VM_ID']").val(vmID);
            $("#formHis").submit();
        }

        function funcOnClick(systemID, systemName, threshold) {
            $("input[name='SYSTEM_ID']").val(systemID);
            $("input[name='SYSTEM_NAME']").val(systemName);
            $("input[name='THRESHOLD']").val(threshold);
            $("#formHis2").submit();
        }

        function refreshCurrentUser() {
            $("#usersNumber").text("");
            $.ajaxGet("@Url.Content("~/UserToken/GetCurrentUsers")", null, function (data) {
                if (data != null) {
                    $("#usersNumber").text(data);
                }
            });
        }

        function refreshHealthCurrentView() {
            $("#healthCurrent").html("");
            $("#alertsNumber").text("");

            $.ajaxGet("@Url.Content("~/HealthCurrent/GetCurrentView")", null, function (data) {
                var alertsName = [];

                if ((data != null) && (data.m_Item1 != null) && (data.m_Item1.length > 0)) {
                    var alertsNumber = 0;

                    for (var item1Index = 0; item1Index < data.m_Item1.length; item1Index++) {
                        var html = '<div class="col-md-3">' +
                            '<div class="widget">' +
                            '<div class="widget-head">' +
                            '<div class="pull-left">' + data.m_Item1[item1Index].NAME + '</div>' +
                            '<div class="clearfix"></div>' +
                            '</div><!-- widget-head -->' +
                            '<div class="widget-content">' +
                            '<div class="table-responsive">' +
                            '<table class="table table-striped table-bordered table-hover">' +
                            '<thead>' +
                            '<tr>' +
                            '<th>狀態</th>' +
                            '<th>主機/事件</th>' +
                            '<th>AP Server IP</th>' +
                            '</tr>' +
                            '</thead>' +
                            '<tbody>';

                        for (var item2Index = 0; item2Index < data.m_Item2.length; item2Index++) {
                            if (data.m_Item1[item1Index].ID == data.m_Item2[item2Index].SYSTEM_ID) {
                                html += '<tr onclick="rowOnClick(\'' + data.m_Item2[item2Index].SYSTEM_ID +
                                    '\',\'' + data.m_Item2[item2Index].SYSTEM_NAME +
                                    '\',\'' + data.m_Item2[item2Index].VM_ID + '\');" style="cursor:pointer">' +
                                    '<td class="text-center">';
                                if (data.m_Item2[item2Index].STATUS) {
                                    html += '<span class="label label-success">上線</span>';
                                }
                                else {
                                    html += '<span class="label label-danger">離線</span>';
                                    alertsNumber += 1;
                                    alertsName.push(data.m_Item2[item2Index].VM_ID + '(' + data.m_Item2[item2Index].VM_IPv4 + ') 離線');
                                }

                                html += '</td>' +
                                    '<td>' + data.m_Item2[item2Index].VM_ID + '</td>' +
                                    '<td>' + data.m_Item2[item2Index].VM_IPv4 + '</td>' +
                                    '</tr>';
                            }
                        }

                        if (data.m_Item1[item1Index].KEY_FUNCTION) {
                            html += '<tr onclick="funcOnClick(\'' + data.m_Item1[item1Index].ID +
                                '\',\'' + data.m_Item1[item1Index].NAME + '\',' + data.m_Item1[item1Index].THRESHOLD + ');" style="cursor:pointer">' +
                                '<td></td><td><span name=\'' + data.m_Item1[item1Index].ID + '\'>重要事件</span></td><td></td>' +
                                '</tr>';
                        }

                        html += '</tbody>' +
                            '</table>' +
                            '</div>' +
                            '</div>' +
                            '</div>' +
                            '</div>';

                        $('#healthCurrent').append(html);
                    }
                    $('#alertsNumber').text(alertsNumber);
                }
                else {
                    $('#alertsNumber').text('0');
                }

                if ((data != null) && (data.m_Item3 != null) && (data.m_Item3.length > 0)) {
                    for (var item3Index = 0; item3Index < data.m_Item3.length; item3Index++) {
                        $('span[name="' + data.m_Item3[item3Index].SYSTEM_ID + '"]').addClass('label label-danger');
                        alertsName.push(data.m_Item3[item3Index].SYSTEM_NAME + '的' +
                            data.m_Item3[item3Index].FUNCTION_NAME + '(' +
                            (data.m_Item3[item3Index].IPv4 != null ? data.m_Item3[item3Index].IPv4 : '')  + ') 超過Threshold');
                    }
                    $('#eventsNumber').text(data.m_Item3.length);
                }
                else {
                    $('#eventsNumber').text('0');
                }

                if (alertsName.length > 0) {
                    $('#alerts .modal-body').html(alertsName.join('<br />'));
                    // https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
                    document.getElementById('sound').play();
                    $('#alerts').modal('show');
                }
                else {
                    $('#alerts').modal('hide');
                }
            });
        }
    </script>
}
<audio id="sound" loop preload="auto">
    <source src="@Url.Content("~/Content/Responding5.wav")" type="audio/wav" />
</audio>
<form method="post" id="formHis" action="@Url.Action("EMIC2_His","Rpt")">
    <input type="hidden" name="SYSTEM_ID" />
    <input type="hidden" name="SYSTEM_NAME" />
    <input type="hidden" name="VM_ID" />
</form>
<form method="post" id="formHis2" action="@Url.Action("EMIC2_His2","Rpt")">
    <input type="hidden" name="SYSTEM_ID" />
    <input type="hidden" name="SYSTEM_NAME" />
    <input type="hidden" name="THRESHOLD" />
</form>
<!-- Table -->
<div class="row" id="healthCurrent">
</div>

HealthCheck/Health.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <!-- Title and other stuffs -->
    <title>EMIC APM管理儀表板</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <!-- Stylesheets -->
    @*<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />*@
    <!-- Font awesome icon -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    @*<link href="~/Content/fullcalendar.min.css" rel="stylesheet" />*@

    <!-- Main stylesheet -->
    @*<link href="~/Content/style.css" rel="stylesheet" />*@
    <link href="~/Content/Site.css" rel="stylesheet" />
    <!-- Widgets stylesheet -->
    @*<link href="~/Content/widgets.css" rel="stylesheet" />*@

    @*<link href="~/Content/morris.min.css" rel="stylesheet" />*@
    @RenderSection("styles", false)

    <!--[if lt IE 9]>
    <script src="~/Scripts/html5shiv.js"></script>
    <![endif]-->
    <!-- Favicon -->
    <link rel="shortcut icon" href="./img/icon.ico" />
    <link rel="bookmark" href="./img/icon.ico" />

    <!-- JS -->
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    @*<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>*@
    @*<script src="~/Scripts/fullcalendar/fullcalendar.min.js"></script>*@
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    @*<script src="~/Scripts/raphael.js"></script>*@
    @*<script src="~/Scripts/morris.min.js"></script>*@
    <script src="~/Scripts/ajaxExtensions.js"></script>
    @RenderSection("scripts", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("管理儀表板", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("System", "SystemInfo", "Admin")</li>
                    <li>@Html.ActionLink("VM", "VMInfo", "Admin")</li>
                    <li>@Html.ActionLink("Target", "HealthTarget", "Admin")</li>
                    <li>@Html.ActionLink("Notification", "NotificationInfo", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>
    <!-- Footer starts -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Copyright info -->
                    <p class="copy">Copyright &copy; 2019 | <a href="#">EMIC</a> </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer ends -->
    <!-- Modal -->
    <div class="modal fade" id="alerts" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span class="glyphicon glyphicon-lock"></span> 警示</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> 關閉</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="infos" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><span class="glyphicon glyphicon-lock"></span>訊息</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</body>
</html>

HealthCheck/Health.Web/Views/Shared/_HealthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <!-- Title and other stuffs -->
    <title>EMIC APM監控儀表板</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <!-- Stylesheets -->
    @*<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <!-- Font awesome icon -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    @*<link href="~/Content/fullcalendar.min.css" rel="stylesheet" />*@

    <!-- Main stylesheet -->
    <link href="~/Content/style.css" rel="stylesheet" />
    <!-- Widgets stylesheet -->
    <link href="~/Content/widgets.css" rel="stylesheet" />

    <link href="~/Content/morris.min.css" rel="stylesheet" />
    @RenderSection("styles", false)

    <!--[if lt IE 9]>
    <script src="~/Scripts/html5shiv.js"></script>
    <![endif]-->
    <!-- Favicon -->
    <link rel="shortcut icon" href="./img/icon.ico" />
    <link rel="bookmark" href="./img/icon.ico" />

    <!-- JS -->
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/raphael.js"></script>
    <script src="~/Scripts/morris.min.js"></script>
    <script src="~/Scripts/ajaxExtensions.js"></script>
    @RenderSection("scripts", false)
</head>

<body>
    <!-- Header starts -->
    <header>
        <div class="container">
            <div class="row">
                <!-- Logo section -->
                <a href="@Url.Action("EMIC2_Current","Rpt")">
                    <div class="col-md-2 col-xs-2">
                        <!-- Logo. -->
                        <div class="logo">

                        </div>
                    </div>
                </a>
                <!-- Logo ends -->
                <!-- Data section -->
                <div class="col-md-5 col-xs-10 pull-right">
                    <div class="header-data pull-right">

                        <!-- Traffic data -->
                        <div class="hdata">
                            <div class="mcol-left">
                                <!-- Icon with red background -->
                                <i class="fa fa-bell bred"></i>
                            </div>
                            <div class="mcol-right">
                                <!-- Number of visitors -->
                                <p><span id="alertsNumber"></span><em>狀態警示</em></p>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <!-- Event data -->
                        <div class="hdata">
                            <div class="mcol-left">
                                <!-- Icon with red background -->
                                <i class="fa fa-bolt bred"></i>
                            </div>
                            <div class="mcol-right">
                                <!-- Number of visitors -->
                                <p><span id="eventsNumber"></span><em>事件警示</em></p>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <!-- Members data -->
                        <div class="hdata">
                            <div class="mcol-left">
                                <!-- Icon with blue background -->
                                <i class="fa fa-user bblue"></i>
                            </div>
                            <div class="mcol-right">
                                <!-- Number of visitors -->
                                <p><span id="usersNumber"></span><em>上線人數</em></p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </header>

    <!-- Header ends -->
    <!-- Main content starts -->

    <div class="content">
        <!-- Main bar -->
        <div class="mainbar">

            <!-- Page heading -->
            <div class="page-head">
                <h2 class="pull-left">
                    <i class="fa fa-home"></i> @ViewBag.Title
                </h2>
                <div class="clearfix"></div>

            </div>
            <!-- Page heading ends -->
            <!-- Matter -->
            <div class="matter">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
            <!-- Matter ends -->

        </div>

        <!-- Mainbar ends -->
        <div class="clearfix"></div>

    </div>
    <!-- Content ends -->
    <!-- Footer starts -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Copyright info -->
                    <p class="copy">Copyright &copy; 2019 | <a href="#">EMIC</a> </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer ends -->
    <!-- Modal -->
    <div class="modal fade" id="alerts" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span class="glyphicon glyphicon-lock"></span> 警示</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> 關閉</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

HealthCheck/Health.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>